version: '3'

volumes:
  send_and_expire_local_postgres_data: {}
  send_and_expire_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: send_and_expire_local_django
    container_name: send_and_expire_local_django
    depends_on:
      - postgres
      - redis
      - mailhog
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: send_and_expire_production_postgres
    container_name: send_and_expire_local_postgres
    volumes:
      - send_and_expire_local_postgres_data:/var/lib/postgresql/data:Z
      - send_and_expire_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

#  docs:
#    image: send_and_expire_local_docs
#    container_name: send_and_expire_local_docs
#    build:
#      context: .
#      dockerfile: ./compose/local/docs/Dockerfile
#    env_file:
#      - ./.envs/.local/.django
#    volumes:
#      - ./docs:/docs:z
#      - ./config:/app/config:z
#      - ./send_and_expire:/app/send_and_expire:z
#    ports:
#      - "7000:7000"
#    command: /start-docs

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: send_and_expire_local_mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: send_and_expire_local_redis

  celeryworker:
    <<: *django
    image: send_and_expire_local_celeryworker
    container_name: send_and_expire_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: send_and_expire_local_celerybeat
    container_name: send_and_expire_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: send_and_expire_local_flower
    container_name: send_and_expire_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
